### PR TITLE
Updated UML and XMI namespaces from 13 to 16

### LINKED ISSUE #7: Namespace issues with UML and XMI having 2013 vs 2016 versions
Right now in the round-trip task, the `<profiles>` tag is entirely missing because:

```
       -    <profiles>
       -      <uml:Profile xmlns:uml="http://www.omg.org/spec/UML/20161101" xmlns:xmi="http://www.omg.org/spec/XMI/20161101" xmi:id="thecustomprofile" nsPrefix="thecustomprofile" name="thecustomprofile" metamodelReference="mmref01">
```

The `<uml:Profile>` tag uses:
* `xmlns:uml="http://www.omg.org/spec/UML/20161101"`
* `xmlns:xmi="http://www.omg.org/spec/XMI/20161101"`

But the rest of the document uses:
* `xmlns:uml="http://www.omg.org/spec/UML/20131001"`
* `xmlns:xmi="http://www.omg.org/spec/XMI/20131001"`

The way to solve this is to only apply the newer namespace on this particular Profile element. This means that all the 'uml' and 'xmi' element inside here need to be a different set of Ruby classes that inherit from the old version (2013).

e.g. `uml:Profile` contains `ownedComment`, `packageImport`, `packagedElement` etc.

Potential solution:

```ruby
class Uml2016::OwnedComment < Uml2013::OwnedComment
  xml do
    # ...
    namespace "http://www.omg.org/spec/UML/20161101", "uml"
  end
end

class Uml2016::Profile < Shale::Mapper
  attribute :owned_comment, Uml2016::OwnedComment
  xml do
    root 'Profile'
    namespace "http://www.omg.org/spec/UML/20161101", "uml"
    map_attribute `ownedComment`, to: :owned_comment
  end
end
```

### PR DESCRIPTION
**Pull request by MuhammadAhsan252**
This PR updates namespaces and mapping elements and attributes for the document parsing.

closes #7

### CODE REVIEW

**Comment by MuhammadAhsan252** [comment]
@ronaldtse Support of two different versions **UML** and **XMI** namespaces are now working fine except for one error.
Shale doesn’t support parent and child separate namespaces, for example.
```
class Name < Shale::Mapper
  attribute :name, Shale::Type::String
  xml do 
    map_element :name, to: :name, namespace: "new_address", prefix: "ns1" 
  end
end
class Person < Shale::Mapper
  attribute :first_name, Name
  attribute :last_name, Shale::Type::String
  attribute :age, Shale::Type::Integer
  xml do
    root 'person'
    map_element 'first_name', to: :first_name, namespace: 'new_address', prefix: 'ns1'
    map_element 'last_name', to: :last_name, namespace: 'http://ns2.com/', prefix: 'ns2'
    map_attribute 'age', to: :age, namespace: 'http://ns2.com/', prefix: 'ns2'
  end
end
```
Changing Shale’s example to our scenario below.
Just like `xmi:XMI` set `UML` and `XMI` to a different URL than `uml:Profile` element.
Setting `ns1` to a different URL than the `person`’s(already set).
```
person = Person.from_xml(<<~DATA)
<person xmlns:ns1="http://ns1.com/" xmlns:ns2="http://ns2.com/" ns2:age="50">
  <ns1:first_name xmlns:ns1="new_address">
    <ns1:name>John</ns1:name>
  </ns1:first_name>
  <ns2:last_name>Doe</ns2:last_name>
</person>
DATA
```
This will result in NO namespace in the `name` element, which fails to match in specs.

```
<person xmlns:ns2="http://ns2.com/" xmlns:ns1="new_address" ns2:age="50">
 <ns1:first_name>
  <ns1:name>John</ns1:name>
 </ns1:first_name>
 <ns2:last_name>Doe</ns2:last_name>
</person>
```

How do you suggest to handle this scenario?

**Comment by ronaldtse** [comment]
@MuhammadAhsan252 this is exactly as described in #7 .

Let's do this: consider the "namespace" a part of the "element name". 

This means in the 2nd case, "ns1:first_name" is actually "new_address:first_name".

Then you can see that actually when a namespace differs, the elements are completely different.

In our case of 2013 vs 2016 versions, you will need to use 2 classes to deal with the 2 different elements ("class Profile2013" vs "class Profile2016"). These two classes can share code through inheritance, but they are different objects.

e.g.
```
class Uml2013::OwnedComment < Shale::Mapper
  xml do
    # ...
    namespace "http://www.omg.org/spec/UML/20131001", "uml"
  end
end

class Uml2016::OwnedComment < Uml2013::OwnedComment
  xml do
    # ...
    namespace "http://www.omg.org/spec/UML/20161101", "uml"
  end
end

class Uml2016::Profile < Shale::Mapper
  attribute :owned_comment, Uml2016::OwnedComment
  xml do
    root 'Profile'
    namespace "http://www.omg.org/spec/UML/20161101", "uml"
    map_attribute `ownedComment`, to: :owned_comment
  end
end
```

There are ways to simplify this arrangement such as:
* https://github.com/lutaml/shale/issues/7
* https://github.com/lutaml/shale/issues/4

**Review by ronaldtse — APPROVED** [review]

**Comment by MuhammadAhsan252** [comment]
We can parse the file using the approach you mentioned above but there is problem in roundtrip. When generating the **XML** **Shale** adds all the namespaces to the root of the document.
If we have multiple tags with different namespaces the **Shale** will move all the namespaces to the root tag and the generated **XML** will only contain one of the namespace that was encountered last and it will not contain any namespaces in the tags and will fail the comparison.
One approach is to tell **Shale** to keep the namespaces in the current tag by adding a flag like `preserve_namespaces: true` in the `xml` block.
Are you good with this approach ?

**Comment by ronaldtse** [comment]
@MuhammadAhsan252 yes, the `preserve_namespaces: true` approach as a temporary fix is acceptable. 

This is clearly a problem in Shale because an XML file can contain two different namespaces with an identical prefix (it's okay because of encapsulation).

**Comment by ronaldtse** [comment]
@MuhammadAhsan252 can you help create the bug at https://github.com/lutaml/shale? Thanks!

**Comment by ronaldtse** [comment]
@kwkwan can you please help fix the conflict and merge this first? You can use the `gh` command to pull this PR and fix the conflict. Thanks.

**Pull request merged**
